# -*- coding: utf-8 -*-
"""IELTS Voice-to-Voice AI Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SojqX1jsKD0FMrYhmWHSOJK0GshrYpve
"""

!pip install -q openai-whisper
!pip install -q cohere
!pip install -q gTTS
!pip install -q soundfile
!pip install -q ffmpeg-python

!apt-get update
!apt-get install -y ffmpeg

import whisper
import cohere
from gtts import gTTS

print("جميع المكتبات تعمل بنجاح ✅")

from google.colab import files

uploaded = files.upload()

import os
print(os.listdir())

import whisper

model = whisper.load_model("base")

result = model.transcribe("vioce.mp4")

print(result["text"])

import cohere

co = cohere.Client("cohere_WhJwhh3f0IiIe6YQQ4s3AjwvR2uC7M4Shf4e2tt92JsgyE")

user_text = result["text"]

prompt = f"""
You are an IELTS Speaking Examiner.

The student's answer is:
{user_text}

Reply naturally as an IELTS examiner.
Correct grammar if needed.
Estimate the IELTS band.
"""

response = co.chat(
    message=prompt
)

print(response.text)

from gtts import gTTS

tts = gTTS(response.text, lang="en")

tts.save("reply.mp3")

from IPython.display import Audio

Audio("reply.mp3")

user_text = result["text"]

prompt = f"""
You are a professional IELTS Speaking Examiner.

The student answered:
{user_text}

Your tasks:
1. Respond like a real IELTS examiner.
2. Give feedback on:
   - Grammar
   - Vocabulary
   - Fluency
   - Pronunciation (based on the transcript only)
3. Estimate an IELTS Band score from 1 to 9.
4. Ask the next IELTS Speaking question.

Keep your response short and friendly.
"""

from gtts import gTTS
from IPython.display import Audio

tts = gTTS(text=response.text, lang="en")
tts.save("reply.mp3")

Audio("reply.mp3", autoplay=True)

!pip install -q ffmpeg-python

from IPython.display import Javascript
from google.colab import output
from base64 import b64decode
import ffmpeg

def record_audio(filename='recorded.wav', seconds=10):
    js = f'''
    async function record() {{
      const stream = await navigator.mediaDevices.getUserMedia({{audio: true}});
      const recorder = new MediaRecorder(stream);
      const chunks = [];

      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.start();

      await new Promise(r => setTimeout(r, {seconds * 1000}));

      recorder.stop();

      const blob = await new Promise(resolve => {{
        recorder.onstop = () => resolve(new Blob(chunks));
      }});

      const arrayBuffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(arrayBuffer);
      let binary = '';
      bytes.forEach(b => binary += String.fromCharCode(b));

      return btoa(binary);
    }}
    record();
    '''

    audio_data = output.eval_js(js)

    with open('temp.webm', 'wb') as f:
        f.write(b64decode(audio_data))

    (
        ffmpeg
        .input('temp.webm')
        .output(filename)
        .overwrite_output()
        .run(quiet=True)
    )

    print(f'Audio saved as {filename}')

record_audio()

import whisper

model = whisper.load_model('base')

result = model.transcribe('recorded.wav')

user_text = result['text']

print('You said:')
print(user_text)

import cohere

# Replace 'YOUR_API_KEY' with your actual Cohere API key.
# You can find your API key at https://dashboard.cohere.com/api-keys.
co = cohere.Client('YOUR_API_KEY')

prompt = f'''
You are a professional IELTS Speaking Examiner.

Student answer:
{user_text}

Give:
- Grammar feedback
- Vocabulary feedback
- Fluency feedback
- Estimated IELTS Band
- Ask the next IELTS question

Keep it short and natural.
'''

response = co.chat(message=prompt)

print(response.text)

"""### IELTS Speaking Practice Loop

This loop will simulate an IELTS Speaking test. It will record your voice, transcribe it, send it to the Cohere examiner, and play back the examiner's response. The conversation will continue until you say 'stop'.

**Instructions:**
1.  Run the cell below.
2.  When prompted, speak your answer after the beep. The recording will last 10 seconds.
3.  Listen to the examiner's feedback and next question.
4.  Repeat until you wish to stop. To stop the conversation, simply say 'stop' at any point during your answer.


"""

# Initialize Whisper model (if not already done)
# This is done here to ensure the loop can run independently if needed.
# If you have already loaded the model, this line will just re-initialize it.
model = whisper.load_model('base')

# Initialize conversation history for Cohere chat
conversation_history = []

print("IELTS Examiner: Hello, what's your name and where are you from?")
examiner_response_text = "Hello, what's your name and where are you from?"

tts = gTTS(text=examiner_response_text, lang='en')
tts.save("examiner_intro.mp3")
Audio("examiner_intro.mp3", autoplay=True)

# Add the initial examiner message to history
conversation_history.append({"role": "CHATBOT", "message": examiner_response_text})

while True:
    print("\n--- Recording your answer ---")
    # Record audio for 10 seconds (using a new filename for each turn)
    record_audio('recorded_loop.wav', seconds=10)

    # Transcribe the recorded audio
    result = model.transcribe('recorded_loop.wav')
    user_text = result['text']
    print(f"You said: {user_text}")

    # Add user's message to conversation history
    conversation_history.append({"role": "USER", "message": user_text})

    if "stop" in user_text.lower():
        print("IELTS Examiner: Thank you. That concludes our speaking test.")
        break

    # Construct the prompt for the Cohere API
    # This prompt is designed to get feedback and the next question
    prompt_for_cohere = f'''
You are a professional IELTS Speaking Examiner.

The student answered:
{user_text}

Your tasks:
1. Respond like a real IELTS examiner.
2. Give feedback on:
   - Grammar
   - Vocabulary
   - Fluency
   - Pronunciation (based on the transcript only)
3. Estimate an IELTS Band score from 1 to 9.
4. Ask the next IELTS Speaking question.

Keep your response short and friendly.
'''

    try:
        # Send the conversation to Cohere
        cohere_response = co.chat(
            message=prompt_for_cohere,
            chat_history=conversation_history
        )

        examiner_response_text = cohere_response.text
        print("\nIELTS Examiner:")
        print(examiner_response_text)

        # Add examiner's response to conversation history
        conversation_history.append({"role": "CHATBOT", "message": examiner_response_text})

        # Convert examiner's response to speech and play it
        tts = gTTS(text=examiner_response_text, lang='en')
        tts.save("examiner_reply.mp3")
        Audio("examiner_reply.mp3", autoplay=True)

    except Exception as e:
        print(f"An error occurred with Cohere API: {e}")
        print("Please check your API key and try again. Stopping the loop.")
        break

from gtts import gTTS
from IPython.display import Audio

tts = gTTS(text=response.text, lang='en')

tts.save('reply.mp3')

Audio('reply.mp3', autoplay=True)